Jest test

diff --git a/.github/workflows/Main.yml b/.github/workflows/Main.yml
--- a/.github/workflows/Main.yml
+++ b/.github/workflows/Main.yml
@@ -49,75 +49,75 @@ jobs:
       - name: Run ESLint
         run: npm run lint
 
-  # unit-tests:
-  #   needs: lint
-  #   runs-on: ubuntu-latest
-  #   outputs:
-  #     jest_exit_code: ${{ steps.set_exit_code.outputs.exit_code }}
-  #   steps:
-  #     - uses: actions/checkout@v3
-  #       with:
-  #         fetch-depth: 0
-  #         token: ${{ secrets.MY_GH_TOKEN }}
-  #     - name: Cache Node Modules
-  #       uses: actions/cache@v2
-  #       with:
-  #         path: node_modules
-  #         key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
-  #         restore-keys: |
-  #           ${{ runner.os }}-node-
-  #     - name: Set up Node.js
-  #       uses: actions/setup-node@v2
-  #       with:
-  #         node-version: "20"
-  #     - name: Install dependencies
-  #       run: npm install --legacy-peer-deps
-  #     - name: Run Jest Tests
-  #       id: set_exit_code
-  #       run: |
-  #         set +e
-  #         npm run test:unit -- --coverage || exit_code=$?
-  #         echo "::set-output name=exit_code::$exit_code"
-  #         mv coverage/lcov-report ./coverage-report
-  #         echo "exit_code=$exit_code"
-  #         set -e
-  #     - name: Upload Jest Test Results
-  #       uses: actions/upload-artifact@v3
-  #       with:
-  #         name: jest-coverage-report
-  #         path: coverage-report/
+  unit-tests:
+    needs: lint
+    runs-on: ubuntu-latest
+    outputs:
+      jest_exit_code: ${{ steps.set_exit_code.outputs.exit_code }}
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+          token: ${{ secrets.MY_GH_TOKEN }}
+      - name: Cache Node Modules
+        uses: actions/cache@v2
+        with:
+          path: node_modules
+          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
+          restore-keys: |
+            ${{ runner.os }}-node-
+      - name: Set up Node.js
+        uses: actions/setup-node@v2
+        with:
+          node-version: "20"
+      - name: Install dependencies
+        run: npm install --legacy-peer-deps
+      - name: Run Jest Tests
+        id: set_exit_code
+        run: |
+          set +e
+          npm run test:unit --coverage || exit_code=$?
+          echo "::set-output name=exit_code::$exit_code"
+          mv coverage/lcov-report ./coverage-report
+          echo "exit_code=$exit_code"
+          set -e
+      - name: Upload Jest Test Results
+        uses: actions/upload-artifact@v3
+        with:
+          name: jest-coverage-report
+          path: coverage-report/
 
-  # post-coverage-comment-jest:
-  #   needs: unit-integration-tests
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - uses: actions/github-script@v4
-  #       if: github.event_name == 'pull_request'
-  #       with:
-  #         script: |
-  #           github.rest.issues.createComment({
-  #             issue_number: context.payload.pull_request.number,
-  #             owner: context.repo.owner,
-  #             repo: context.repo.repo,
-  #             body: `Los reportes de cobertura están disponibles en los artefactos: [Ver artefactos](${{ github.run_id }})`
-  #           });
+  post-coverage-comment-jest:
+    needs: unit-test
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/github-script@v4
+        if: github.event_name == 'pull_request'
+        with:
+          script: |
+            github.rest.issues.createComment({
+              issue_number: context.payload.pull_request.number,
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              body: `Los reportes de cobertura están disponibles en los artefactos: [Ver artefactos](${{ github.run_id }})`
+            });
 
-  # jest-validation:
-  #   needs: unit-integration-tests
-  #   runs-on: ubuntu-latest
-  #   if: ${{ needs.unit-integration-tests.outputs.jest_exit_code != '0' }}
-  #   steps:
-  #     - name: Handle Jest Failure
-  #       run: |
-  #         echo "Jest tests failed. Reverting to previous version..."
-  #         git config --global user.email "20210658@uthh.edu.mx"
-  #         git config --global user.name "rodrigo3829l"
-  #         git reset --hard HEAD^
-  #         git push origin main --force
+  jest-validation:
+    needs: unit-test
+    runs-on: ubuntu-latest
+    if: ${{ needs.unit-test.outputs.jest_exit_code != '0' }}
+    steps:
+      - name: Handle Jest Failure
+        run: |
+          echo "Jest tests failed. Reverting to previous version..."
+          git config --global user.email "20210658@uthh.edu.mx"
+          git config --global user.name "rodrigo3829l"
+          git reset --hard HEAD^
+          git push origin main --force
 
   sonar-scan:
-    needs: lint
-    # if: ${{ needs.unit-integration-tests.outputs.jest_exit_code == '0' }}
+    needs: unit-test
+    if: ${{ needs.unit-test.outputs.jest_exit_code == '0' }}
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
@@ -145,7 +145,7 @@ jobs:
 
   snyk-scan:
     needs: sonar-scan
-    # if: ${{ needs.unit-integration-tests.outputs.jest_exit_code == '0' }}
+    if: ${{ needs.unit-test.outputs.jest_exit_code == '0' }}
     runs-on: ubuntu-latest
     outputs:
       snyk_exit_code: ${{ steps.set_exit_code.outputs.exit_code }}
@@ -196,8 +196,8 @@ jobs:
 
   deploy-staging:
     needs: snyk-scan
-    # if: ${{ needs.unit-integration-tests.outputs.jest_exit_code == '0' && needs.snyk-scan.outputs.snyk_exit_code == '0' }}
-    if: ${{ needs.snyk-scan.outputs.snyk_exit_code == '0' }}
+    if: ${{ needs.unit-test.outputs.jest_exit_code == '0' && needs.snyk-scan.outputs.snyk_exit_code == '0' }}
+    # if: ${{ needs.snyk-scan.outputs.snyk_exit_code == '0' }}
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
@@ -246,7 +246,7 @@ jobs:
 
   e2e-tests-staging:
     needs: deploy-staging
-    if: ${{ needs.unit-integration-tests.outputs.jest_exit_code == '0' && needs.snyk-scan.outputs.snyk_exit_code == '0' }}
+    if: ${{ needs.unit-test.outputs.jest_exit_code == '0' && needs.snyk-scan.outputs.snyk_exit_code == '0' }}
     runs-on: ubuntu-latest
     outputs:
       cypress_exit_code: ${{ steps.set_exit_code.outputs.exit_code }}
@@ -352,10 +352,10 @@ jobs:
           "
 
   notify-pr-success:
-    # if: ${{ needs.unit-integration-tests.outputs.jest_exit_code == '0' || needs.snyk-scan.outputs.snyk_exit_code == '0' }}
-    if: ${{ needs.snyk-scan.outputs.snyk_exit_code == '0' }}
+    if: ${{ needs.unit-test.outputs.jest_exit_code == '0' || needs.snyk-scan.outputs.snyk_exit_code == '0' }}
+    # if: ${{ needs.snyk-scan.outputs.snyk_exit_code == '0' }}
     runs-on: ubuntu-latest
-    # needs: [unit-integration-tests, snyk-scan, sonar-scan]
+    needs: [unit-test, snyk-scan, sonar-scan]
     needs: [snyk-scan, sonar-scan]
     steps:
       - uses: actions/github-script@v4
@@ -378,10 +378,10 @@ jobs:
             }
 
   notify-pr-failed:
-    # if: ${{ needs.unit-integration-tests.outputs.jest_exit_code == '0' || needs.snyk-scan.outputs.snyk_exit_code == '0' }}
-    if: ${{ needs.snyk-scan.outputs.snyk_exit_code == '0' }}
+    if: ${{ needs.unit-test.outputs.jest_exit_code == '0' || needs.snyk-scan.outputs.snyk_exit_code == '0' }}
+    # if: ${{ needs.snyk-scan.outputs.snyk_exit_code == '0' }}
     runs-on: ubuntu-latest
-    # needs: [unit-integration-tests, snyk-scan, sonar-scan]
+    needs: [unit-test, snyk-scan, sonar-scan]
     needs: [snyk-scan, sonar-scan]
     steps:
       - uses: actions/github-script@v4
@@ -404,8 +404,8 @@ jobs:
             }
 
   notify-email:
-    # needs: [unit-integration-tests, snyk-scan, sonar-scan]
-    needs: [snyk-scan, sonar-scan]
+    needs: [unit-test, snyk-scan, sonar-scan]
+    # needs: [snyk-scan, sonar-scan]
     runs-on: ubuntu-latest
     steps:
       - name: Prepare SHA and Run ID
